services:
  valtheradb:
    build: .
    image: valtheradb-server
    container_name: valtheradb
    ports:
      - "14785:14785"
      #- "14786:14786" # HTTPS (enable when SSL_CERT and SSL_KEY are set)
    env_file:
      - .env
    volumes:
      - ./volumes:/app/volumes
