name: Build

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      files: "dist gui package.json .env.example dockerfile app.js"
      scriptsHandling: custom-list
      customScripts: start,server,mgmt,right
