name: Build

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      files: "dist gui package.json gui-script/dist .env.example dockerfile app.js"
      customCommands: |
        cd gui-script
        npm i
        npm run build
        cd ..
      scriptsHandling: custom-list
      customScripts: start,server,mgmt,right
